"""add_abn_ph_em to business table

Revision ID: f5b3363fba33
Revises: 3cc8da8bf82e
Create Date: 2026-05-05 06:05:41.360580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b3363fba33'
down_revision: Union[str, Sequence[str], None] = '3cc8da8bf82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('abn', sa.String(), nullable=True))
    op.add_column('business', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('business', sa.Column('email', sa.String(), nullable=True))
    op.add_column('business', sa.Column('is_supplier', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'is_supplier')
    op.drop_column('business', 'email')
    op.drop_column('business', 'phone')
    op.drop_column('business', 'abn')
    # ### end Alembic commands ###
